-- Criação da tabela de Usuários
CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

-- Criação da tabela de Categorias
-- Relacionada ao Usuário (um usuário possui N categorias)
CREATE TABLE CATEGORIA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_USUARIO_CATEGORIA FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIO(ID) ON DELETE CASCADE
);

-- Criação da tabela de Tarefas
-- Relacionada ao Usuário e à Categoria
CREATE TABLE TAREFA (
    ID SERIAL PRIMARY KEY,
    DESCRICAO TEXT NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONCLUIDA BOOLEAN DEFAULT FALSE,
    DATA_INICIO TIMESTAMP,
    DATA_FIM TIMESTAMP,
    ID_USUARIO INT NOT NULL,
    ID_CATEGORIA INT,
    CONSTRAINT FK_USUARIO_TAREFA FOREIGN KEY (ID_USUARIO) 
        REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CATEGORIA_TAREFA FOREIGN KEY (ID_CATEGORIA) 
        REFERENCES CATEGORIA(ID) ON DELETE SET NULL
);